[package]
name = "declare-macros"
description = "Macros for the declare crate"
version = "0.1.1"
edition = "2024"
repository = "https://github.com/mcmah309/declare"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
