[package]
name = "declare"
description = "Macros for declaring additional functionality - enums with newtype variants, enums with common accessors, etc."
version = "0.1.2"
edition = "2024"
repository = "https://github.com/mcmah309/declare"
license = "Apache-2.0"
# categories = []
# keywords = []

[dependencies]
declare-macros = { path = "../declare-macros", version = "0.1.2" }

[dev-dependencies]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"] # Used in the root .rs file to enable `#![cfg_attr(docsrs, feature(doc_cfg))]`